checks:
    php:
        code_rating: true
        duplication: false
        verify_property_names: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_methods: true
        single_namespace_per_use: true

tools:
    external_code_coverage: false
    php_code_coverage: false
    php_code_sniffer:
        config: { standard: 'PSR2' }
    php_changetracking: false
    php_sim: false
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: false
    sensiolabs_security_checker: true

filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'features/bootstrap/*'
        - 'dev/*'
        - 'var/*'
        - 'lib/*'
        - 'bin/*'
        - 'vendor/*'

build:
    environment:
        php:
            version: 7.0.8
            ini:
                'always_populate_raw_post_data': '-1'

    tests:
        override:
            - bin/phpspec run --no-interaction --format=pretty
            - bin/behat --no-interaction --no-snippets --stop-on-failure --format=pretty

    dependencies:
        override:
            - { command: 'composer install --no-interaction', idle_timeout: 600 }

    cache:
        directories: [ bin/, ~/.composer/cache ]

build_failure_conditions:
    - 'elements.rating(<= B).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.new.exists'
    - 'project.metric("scrutinizer.quality", < 9.00)'
